export const LABELS = {
  "app.name": "HR Harmony Hub",
  "superAdmin.dashboard.title": "Super Admin Command Center",
  "superAdmin.dashboard.subtitle": "Live control over features, visibility, access, and system experience.",
  "admin.dashboard.title": "Control Center",
  "admin.candidates.title": "Applicants",
  "admin.payroll.title": "Payroll",
  "admin.settings.title": "Settings",
  "employee.dashboard.title": "Employee Dashboard",
  "candidate.details.title": "Candidate Review",
  "nav.superAdmin.dashboard": "Super Admin",
  "nav.admin.dashboard": "Dashboard",
  "nav.admin.candidates": "Applicants",
  "nav.admin.payroll": "Payroll",
  "nav.admin.users": "User Management",
  "nav.admin.settings": "Settings",
  "nav.employee.dashboard": "Dashboard",
  "nav.employee.joiningForm": "Joining Form",
  "nav.hr.dashboard": "HR Dashboard",
  "nav.recruiter.dashboard": "Recruiter Dashboard",
  "nav.candidate.dashboard": "Dashboard",
  "admin.dashboard.subtitle": "Here is your premium admin workspace for hiring, workforce health, payroll visibility, and people operations across the organization.",
  "admin.dashboard.action.users": "User Management",
  "admin.dashboard.hero.eyebrow": "Executive Command",
  "admin.dashboard.hero.title": "See the full HR system in one calm, high-signal workspace.",
  "admin.dashboard.hero.description": "From hiring flow to active workforce coverage, the dashboard keeps the admin portal readable, responsive, and ready for daily decisions without drowning the team in noise.",
  "admin.dashboard.hero.highlight.workforce": "Active workforce",
  "admin.dashboard.hero.highlight.hiring": "Hiring in motion",
  "admin.dashboard.hero.highlight.payroll": "Payroll volume",
  "admin.dashboard.profile.role": "System Administrator",
  "admin.dashboard.profile.subtitle": "You are looking at the highest-level people operations view, where workforce readiness, candidate momentum, and policy approvals all meet in one product-grade interface.",
  "admin.dashboard.stats.candidates": "Total Candidates",
  "admin.dashboard.stats.employees": "Active Employees",
  "admin.dashboard.stats.reviews": "Pending HR Reviews",
  "admin.dashboard.stats.queue": "People Ops Queue",
  "admin.dashboard.widget.workforce": "Workforce Health",
  "admin.dashboard.widget.workforce.subtitle": "A lightweight readiness score built from active employee coverage, department spread, and unresolved approval load.",
  "admin.dashboard.widget.priority": "Admin Priority Stack",
  "admin.dashboard.widget.priority.subtitle": "The most important actions for this portal, expressed as clear progress blocks instead of noisy analytics.",
  "admin.dashboard.table.title": "Employee Roster",
  "admin.dashboard.table.subtitle": "A dynamic employee table ready for pagination, quick scanning, and navigation into the full employee management module.",
  "admin.dashboard.calendar.title": "Executive Calendar",
  "admin.dashboard.calendar.subtitle": "Shared events, approvals, and workforce milestones are organized into a clean monthly calendar so the admin view stays actionable.",
  "admin.dashboard.table.employee": "Employee",
  "admin.dashboard.table.department": "Department",
  "admin.dashboard.table.compensation": "Compensation",
  "admin.dashboard.table.status": "Status",
  "admin.dashboard.table.unassigned": "Unassigned",
  "admin.dashboard.table.employeeId": "Employee ID",
  "admin.dashboard.welcome": "Welcome",
  "admin.dashboard.highlight.workforce.label": "Active workforce",
  "admin.dashboard.highlight.hiring.label": "Hiring in motion",
  "admin.dashboard.highlight.payroll.label": "Payroll volume",
  "admin.dashboard.profile.defaultName": "Admin",
  "admin.dashboard.profile.meta.departments": "Departments",
  "admin.dashboard.profile.meta.leaves": "Pending leaves",
  "admin.dashboard.profile.meta.queue": "Review queue",
  "admin.dashboard.stats.reviews.change": "Needs evaluation action",
  "admin.dashboard.stats.queue.change": "Leave approvals in motion",
  "admin.dashboard.widget.workforce.metric.employees": "Active employees",
  "admin.dashboard.widget.workforce.metric.departments": "Departments covered",
  "admin.dashboard.widget.workforce.metric.approvals": "Pending approvals",
  "admin.dashboard.widget.priority.leave": "Leave approvals",
  "admin.dashboard.widget.priority.reviews": "HR evaluations",
  "admin.dashboard.widget.priority.hiring": "Hiring throughput",
  "admin.dashboard.empty.title": "No employees available",
  "admin.dashboard.empty.description": "Employee records will appear here as soon as the admin workspace has active people data.",
  "admin.candidates.subtitle": "Stage-based workflow with real-time status updates",
  "admin.candidates.search": "Search candidate by name, email, position",
  "admin.candidates.filter.all": "All Statuses",
  "admin.candidates.found": "candidates found",
  "admin.candidates.table.name": "Name",
  "admin.candidates.table.email": "Email",
  "admin.candidates.table.phone": "Phone",
  "admin.candidates.table.position": "Position",
  "admin.candidates.table.status": "Status",
  "admin.candidates.table.appliedAt": "Applied At",
  "admin.candidates.table.actions": "Actions",
  "admin.candidates.action.evaluate": "Evaluate",
  "admin.candidates.action.moveToEmployee": "Move to Employee",
  "admin.candidates.action.assignInternship": "Assign Internship",
  "admin.candidates.action.sendOffer": "Send Offer",
  "admin.candidates.action.sendJoiningForm": "Send Joining Form",
  "admin.candidates.action.delete": "Delete",
  "admin.settings.subtitle": "Centralized runtime configuration for profile, company, security, notifications, uploads, and audit behavior.",
  "admin.settings.section.profile": "Profile Settings",
  "admin.settings.section.company": "Company Settings",
  "admin.settings.section.roles": "Role & Permissions",
  "admin.settings.section.security": "Security",
  "admin.settings.section.notifications": "Notifications",
  "admin.settings.section.preferences": "System Preferences",
  "admin.settings.section.documents": "Document Settings",
  "admin.settings.section.audit": "Audit & Activity",
  "admin.settings.section.runtime": "Runtime Config",
  "common.error": "Error",
  "common.loading": "Loading...",
  "common.loading.settings": "Loading settings...",
  "common.cancel": "Cancel",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.logout": "Logout",
  "common.profile": "Profile",
  "common.saveChanges": "Save Changes",
  "common.resetSection": "Reset Section",
  "common.markAllRead": "Mark all read",
  "layout.portal.department": "HR Department",
  "layout.portal.workspace": "workspace",
  "layout.portal.blurb": "Premium HRMS workspace with live modules, approvals, and activity.",
  "layout.notifications.title": "Notifications",
  "layout.notifications.subtitle": "Recent alerts and updates",
  "layout.notifications.empty": "No notifications yet.",
  "layout.notifications.loading": "Loading notifications...",
  "layout.pendingEmployee.banner": "Please complete your Joining Form to activate your account.",
  "admin.dashboard.highlight.workforce.label": "Active workforce",
  "admin.dashboard.highlight.workforce.note": "total employee records currently managed.",
  "admin.dashboard.highlight.hiring.label": "Hiring in motion",
  "admin.dashboard.highlight.hiring.note": "profiles still waiting on HR review.",
  "admin.dashboard.highlight.payroll.label": "Payroll volume",
  "admin.dashboard.highlight.payroll.note": "leave approvals still need attention.",
  "admin.dashboard.profile.meta.departments": "Departments",
  "admin.dashboard.profile.meta.departments.suffix": "active teams",
  "admin.dashboard.profile.meta.leaves": "Pending leaves",
  "admin.dashboard.profile.meta.leaves.suffix": "approvals",
  "admin.dashboard.profile.meta.queue": "Review queue",
  "admin.dashboard.profile.meta.queue.suffix": "candidate profiles",
  "admin.dashboard.stats.candidates.change": "Pipeline population",
  "admin.dashboard.stats.employees.change.suffix": "total people records",
  "admin.dashboard.stats.reviews.change": "Awaiting structured evaluation",
  "admin.dashboard.stats.queue.change": "Leaves plus candidate actions",
  "admin.candidates.empty.title": "No candidates available",
  "admin.candidates.empty.description": "No data available for the current search or status filter.",
  "admin.candidates.empty.refresh": "Refresh list",
  "admin.candidates.loading": "Loading candidates...",
  "admin.candidates.empty.table": "No data available.",
  "admin.candidates.pagination.showing": "Showing",
  "admin.candidates.pagination.of": "of",
  "admin.candidates.pagination.previous": "Previous",
  "admin.candidates.pagination.next": "Next",
  "admin.candidates.action.more": "More actions for candidate",
  "admin.candidates.action.moving": "Moving...",
  "admin.candidates.action.deleting": "Deleting...",
  "admin.candidates.internship.title": "Assign Internship",
  "admin.candidates.internship.startDate": "Start Date",
  "admin.candidates.internship.endDate": "End Date",
  "admin.candidates.internship.assigning": "Assigning...",
  "admin.candidates.offer.title": "Send Offer Letter",
  "admin.candidates.offer.role": "Role",
  "admin.candidates.offer.salary": "Salary",
  "admin.candidates.offer.joiningDate": "Joining Date",
  "admin.candidates.offer.placeholder.role": "Senior Executive",
  "admin.candidates.offer.placeholder.salary": "25000",
  "admin.candidates.offer.sending": "Sending...",
  "admin.candidates.offer.generate": "Generate & Send Offer",
  "admin.candidates.delete.title": "Delete Candidate",
  "admin.candidates.delete.description": "Are you sure you want to permanently delete this candidate? This action cannot be undone.",
  "admin.candidates.move.title": "Move Candidate To Employee",
  "admin.candidates.move.description": "Move this candidate to Employee? This will continue the onboarding workflow.",
  "admin.candidates.move.confirm": "Move",
  "admin.settings.categories": "Settings Categories",
  "admin.settings.profile.name": "Full Name *",
  "admin.settings.profile.email": "Email *",
  "admin.settings.profile.phone": "Phone Number",
  "admin.settings.profile.changePassword": "Change Password",
  "admin.settings.profile.currentPassword": "Current Password",
  "admin.settings.profile.newPassword": "New Password",
  "admin.settings.profile.confirmPassword": "Confirm Password",
  "admin.settings.profile.changePasswordButton": "Change Password",
  "admin.settings.profile.updatingPassword": "Updating...",
  "admin.settings.company.name": "Company Name *",
  "admin.settings.company.contactEmail": "Contact Email",
  "admin.settings.company.contactPhone": "Contact Phone",
  "admin.settings.company.website": "Website",
  "admin.settings.company.address": "Address",
  "admin.settings.company.description": "Description",
  "admin.settings.company.logo": "Company Logo Upload",
  "admin.settings.company.logo.help": "Use a square JPG or PNG up to 5MB for the cleanest result.",
  "admin.settings.security.otp": "Enable OTP Login",
  "admin.settings.security.2fa": "Enforce 2FA for Admin",
  "admin.settings.security.minLength": "Password Minimum Length",
  "admin.settings.security.sessionTimeout": "Session Timeout (minutes)",
  "admin.settings.security.maxAttempts": "Maximum Login Attempts",
  "admin.settings.security.passwordPolicy": "Password Policy",
  "admin.settings.security.uppercase": "Require Uppercase",
  "admin.settings.security.number": "Require Number",
  "admin.settings.security.special": "Require Special Character",
  "admin.settings.preferences.theme": "Theme",
  "admin.settings.preferences.theme.light": "Light",
  "admin.settings.preferences.theme.dark": "Dark",
  "admin.settings.preferences.defaultPage": "Default Dashboard Page",
  "admin.settings.preferences.language": "Language",
  "admin.settings.preferences.timezone": "Timezone",
  "admin.settings.preferences.dateFormat": "Date Format",
  "admin.settings.preferences.currencyFormat": "Currency Format",
  "admin.settings.documents.allowedTypes": "Allowed File Types (comma separated MIME types)",
  "admin.settings.documents.maxUpload": "Maximum Upload Size (MB)",
  "admin.settings.documents.storage": "Storage Location",
  "admin.settings.documents.naming": "Naming Format",
  "admin.settings.audit.logging": "Enable Logging",
  "admin.settings.audit.retention": "Log Retention Duration (days)",
  "admin.settings.audit.export": "Export Logs",
  "admin.settings.runtime.info": "Edit the live runtime JSON that powers features, labels, permissions, theme, navigation, portal visibility, and route guards. This is the Super Admin control surface for the frontend renderer.",
  "admin.settings.runtime.json": "Runtime Config JSON",
  "admin.settings.saving": "Saving...",
} as const;
