export const DEFAULT_RUNTIME_PERMISSION_ENTRIES = [
  { role: "super_admin", action: "manage_runtime_config", allowed: true },
  { role: "super_admin", action: "view_candidates", allowed: true },
  { role: "super_admin", action: "edit_candidates", allowed: true },
  { role: "super_admin", action: "run_payroll", allowed: true },
  { role: "super_admin", action: "manage_users", allowed: true },
  { role: "admin", action: "manage_runtime_config", allowed: false },
  { role: "admin", action: "view_candidates", allowed: true },
  { role: "admin", action: "edit_candidates", allowed: true },
  { role: "admin", action: "run_payroll", allowed: true },
  { role: "admin", action: "manage_users", allowed: true },
  { role: "hr_manager", action: "manage_runtime_config", allowed: false },
  { role: "hr_manager", action: "view_candidates", allowed: true },
  { role: "hr_manager", action: "edit_candidates", allowed: true },
  { role: "hr_manager", action: "run_payroll", allowed: false },
  { role: "hr_manager", action: "manage_users", allowed: false },
  { role: "recruiter", action: "manage_runtime_config", allowed: false },
  { role: "recruiter", action: "view_candidates", allowed: true },
  { role: "recruiter", action: "edit_candidates", allowed: false },
  { role: "recruiter", action: "run_payroll", allowed: false },
  { role: "recruiter", action: "manage_users", allowed: false },
  { role: "employee", action: "manage_runtime_config", allowed: false },
  { role: "employee", action: "view_candidates", allowed: false },
  { role: "employee", action: "edit_candidates", allowed: false },
  { role: "employee", action: "run_payroll", allowed: false },
  { role: "employee", action: "manage_users", allowed: false },
  { role: "candidate", action: "manage_runtime_config", allowed: false },
  { role: "candidate", action: "view_candidates", allowed: false },
  { role: "candidate", action: "edit_candidates", allowed: false },
  { role: "candidate", action: "run_payroll", allowed: false },
  { role: "candidate", action: "manage_users", allowed: false },
];

