export const DEFAULT_RUNTIME_FEATURES = {
  dashboard: true,
  calendar: true,
  profile: true,
  candidates: true,
  internships: true,
  joiningForms: true,
  employees: true,
  attendance: true,
  leave: true,
  payroll: true,
  letters: true,
  departments: true,
  offboarding: true,
  userManagement: true,
  settings: true,
  applications: true,
  documents: true,
  notifications: true,
};

export const DEFAULT_RUNTIME_LABELS = {
  "app.name": "HR Harmony Hub",
  "superAdmin.dashboard.title": "Super Admin Command Center",
  "superAdmin.dashboard.subtitle": "Live control over features, visibility, access, and system experience.",
  "admin.dashboard.title": "Control Center",
  "admin.candidates.title": "Applicants",
  "admin.payroll.title": "Payroll",
  "admin.settings.title": "Runtime Configuration",
  "nav.admin.dashboard": "Dashboard",
  "nav.admin.calendar": "Calendar",
  "nav.admin.profile": "Profile",
  "nav.admin.candidates": "Applicants",
  "nav.admin.internships": "Internships",
  "nav.admin.joiningForms": "Joining Forms",
  "nav.admin.employees": "Employees",
  "nav.admin.attendance": "Attendance",
  "nav.admin.leave": "Leave",
  "nav.admin.payroll": "Payroll",
  "nav.admin.letters": "Letters",
  "nav.admin.departments": "Departments",
  "nav.admin.offboarding": "Offboarding",
  "nav.admin.users": "User Management",
  "nav.admin.settings": "Settings",
  "nav.superAdmin.dashboard": "Super Admin",
  "nav.employee.dashboard": "Dashboard",
  "nav.employee.joiningForm": "Joining Form",
  "nav.employee.profile": "Profile",
  "nav.employee.attendance": "Attendance",
  "nav.employee.leave": "Leave",
  "nav.employee.payroll": "Payroll",
  "nav.employee.letters": "Letters",
  "nav.hr.dashboard": "HR Dashboard",
  "nav.recruiter.dashboard": "Recruiter Dashboard",
  "nav.candidate.dashboard": "Dashboard",
  "nav.candidate.profile": "My Profile",
  "nav.candidate.applications": "Job Applications",
  "nav.candidate.status": "Application Status",
  "nav.candidate.documents": "Documents",
  "nav.candidate.notifications": "Notifications",
};

export const DEFAULT_RUNTIME_THEME = {
  primaryColor: "#C89B6D",
  mode: "light",
};

export const DEFAULT_PORTAL_VISIBILITY = {
  admin: true,
  employee: true,
  candidate: true,
};

export const DEFAULT_RUNTIME_NAVIGATION = {
  super_admin: [
    { id: "superAdmin.dashboard", path: "/super-admin", labelKey: "nav.superAdmin.dashboard", icon: "ShieldCheck", featureKey: "settings", moduleKey: "settings" },
    { id: "admin.dashboard", path: "/admin/dashboard", labelKey: "nav.admin.dashboard", icon: "LayoutDashboard", featureKey: "dashboard", moduleKey: "dashboard" },
    { id: "admin.candidates", path: "/admin/candidates", labelKey: "nav.admin.candidates", icon: "UserCheck", featureKey: "candidates", moduleKey: "candidates" },
    { id: "admin.payroll", path: "/admin/payroll", labelKey: "nav.admin.payroll", icon: "IndianRupee", featureKey: "payroll", moduleKey: "payroll" },
    { id: "admin.users", path: "/admin/users", labelKey: "nav.admin.users", icon: "ShieldCheck", featureKey: "userManagement", moduleKey: "userManagement" },
    { id: "admin.settings", path: "/admin/settings", labelKey: "nav.admin.settings", icon: "Settings", featureKey: "settings", moduleKey: "settings" },
  ],
  admin: [
    { id: "admin.dashboard", path: "/admin/dashboard", labelKey: "nav.admin.dashboard", icon: "LayoutDashboard", featureKey: "dashboard", moduleKey: "dashboard" },
    { id: "admin.calendar", path: "/admin/calendar", labelKey: "nav.admin.calendar", icon: "CalendarDays", featureKey: "calendar", moduleKey: "dashboard" },
    { id: "admin.profile", path: "/admin/profile", labelKey: "nav.admin.profile", icon: "UserCircle", featureKey: "profile" },
    { id: "admin.candidates", path: "/admin/candidates", labelKey: "nav.admin.candidates", icon: "UserCheck", featureKey: "candidates", moduleKey: "candidates" },
    { id: "admin.internships", path: "/admin/internships", labelKey: "nav.admin.internships", icon: "Briefcase", featureKey: "internships", moduleKey: "candidates" },
    { id: "admin.joiningForms", path: "/admin/joining-forms", labelKey: "nav.admin.joiningForms", icon: "ClipboardCheck", featureKey: "joiningForms", moduleKey: "candidates" },
    { id: "admin.employees", path: "/admin/employees", labelKey: "nav.admin.employees", icon: "Users", featureKey: "employees", moduleKey: "employees" },
    { id: "admin.attendance", path: "/admin/attendance", labelKey: "nav.admin.attendance", icon: "Clock", featureKey: "attendance", moduleKey: "attendance" },
    { id: "admin.leave", path: "/admin/leave", labelKey: "nav.admin.leave", icon: "CalendarDays", featureKey: "leave", moduleKey: "attendance" },
    { id: "admin.payroll", path: "/admin/payroll", labelKey: "nav.admin.payroll", icon: "IndianRupee", featureKey: "payroll", moduleKey: "payroll" },
    { id: "admin.letters", path: "/admin/letters", labelKey: "nav.admin.letters", icon: "FileText", featureKey: "letters", moduleKey: "letters" },
    { id: "admin.departments", path: "/admin/departments", labelKey: "nav.admin.departments", icon: "Building2", featureKey: "departments", moduleKey: "departments" },
    { id: "admin.offboarding", path: "/admin/offboarding", labelKey: "nav.admin.offboarding", icon: "FolderOpen", featureKey: "offboarding" },
    { id: "admin.users", path: "/admin/users", labelKey: "nav.admin.users", icon: "ShieldCheck", featureKey: "userManagement", moduleKey: "userManagement" },
    { id: "admin.settings", path: "/admin/settings", labelKey: "nav.admin.settings", icon: "Settings", featureKey: "settings", moduleKey: "settings" },
  ],
  employee: [
    { id: "employee.dashboard", path: "/employee/dashboard", labelKey: "nav.employee.dashboard", icon: "LayoutDashboard", featureKey: "dashboard" },
    { id: "employee.profile", path: "/employee/profile", labelKey: "nav.employee.profile", icon: "UserCircle", featureKey: "profile" },
    { id: "employee.attendance", path: "/employee/attendance", labelKey: "nav.employee.attendance", icon: "Clock", featureKey: "attendance" },
    { id: "employee.leave", path: "/employee/leave", labelKey: "nav.employee.leave", icon: "CalendarDays", featureKey: "leave" },
    { id: "employee.payroll", path: "/employee/payroll", labelKey: "nav.employee.payroll", icon: "IndianRupee", featureKey: "payroll" },
    { id: "employee.letters", path: "/employee/letters", labelKey: "nav.employee.letters", icon: "FileText", featureKey: "letters" },
    { id: "joining.form", path: "/joining-form", labelKey: "nav.employee.joiningForm", icon: "ClipboardCheck", featureKey: "joiningForms" },
  ],
  hr_manager: [
    { id: "hr.dashboard", path: "/hr/dashboard", labelKey: "nav.hr.dashboard", icon: "LayoutDashboard", featureKey: "dashboard", moduleKey: "dashboard" },
    { id: "admin.candidates", path: "/admin/candidates", labelKey: "nav.admin.candidates", icon: "UserCheck", featureKey: "candidates", moduleKey: "candidates" },
    { id: "admin.letters", path: "/admin/letters", labelKey: "nav.admin.letters", icon: "FileText", featureKey: "letters", moduleKey: "letters" },
  ],
  recruiter: [
    { id: "recruiter.dashboard", path: "/recruiter/dashboard", labelKey: "nav.recruiter.dashboard", icon: "LayoutDashboard", featureKey: "dashboard", moduleKey: "dashboard" },
    { id: "admin.candidates", path: "/admin/candidates", labelKey: "nav.admin.candidates", icon: "UserCheck", featureKey: "candidates", moduleKey: "candidates" },
  ],
  candidate: [
    { id: "candidate.dashboard", path: "/candidate/dashboard", labelKey: "nav.candidate.dashboard", icon: "LayoutDashboard", featureKey: "dashboard" },
    { id: "candidate.profile", path: "/candidate/profile", labelKey: "nav.candidate.profile", icon: "UserCircle", featureKey: "profile" },
    { id: "candidate.applications", path: "/candidate/applications", labelKey: "nav.candidate.applications", icon: "Briefcase", featureKey: "applications" },
    { id: "candidate.status", path: "/candidate/status", labelKey: "nav.candidate.status", icon: "Layers3", featureKey: "applications" },
    { id: "candidate.documents", path: "/candidate/documents", labelKey: "nav.candidate.documents", icon: "FolderOpen", featureKey: "documents" },
    { id: "candidate.notifications", path: "/candidate/notifications", labelKey: "nav.candidate.notifications", icon: "Bell", featureKey: "notifications" },
  ],
};

export const DEFAULT_RUNTIME_ROUTES = {
  "superAdmin.dashboard": { enabled: true, featureKey: "settings", moduleKey: "settings", roles: ["admin"], accessRoles: ["super_admin"], permissionKey: "manage_runtime_config" },
  "admin.dashboard": { enabled: true, featureKey: "dashboard", moduleKey: "dashboard", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.calendar": { enabled: true, featureKey: "calendar", moduleKey: "dashboard", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.profile": { enabled: true, featureKey: "profile", roles: ["admin"] },
  "admin.candidates": { enabled: true, featureKey: "candidates", moduleKey: "candidates", roles: ["admin", "employee"], accessRoles: ["super_admin", "admin", "hr_manager", "recruiter"] },
  "admin.internships": { enabled: true, featureKey: "internships", moduleKey: "candidates", roles: ["admin", "employee"], accessRoles: ["super_admin", "admin", "hr_manager", "recruiter"] },
  "admin.joiningForms": { enabled: true, featureKey: "joiningForms", moduleKey: "candidates", roles: ["admin", "employee"], accessRoles: ["super_admin", "admin", "hr_manager", "recruiter"] },
  "admin.employees": { enabled: true, featureKey: "employees", moduleKey: "employees", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.attendance": { enabled: true, featureKey: "attendance", moduleKey: "attendance", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.leave": { enabled: true, featureKey: "leave", moduleKey: "attendance", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.payroll": { enabled: true, featureKey: "payroll", moduleKey: "payroll", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.letters": { enabled: true, featureKey: "letters", moduleKey: "letters", roles: ["admin", "employee"], accessRoles: ["super_admin", "admin", "hr_manager"] },
  "admin.departments": { enabled: true, featureKey: "departments", moduleKey: "departments", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.offboarding": { enabled: true, featureKey: "offboarding", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.users": { enabled: true, featureKey: "userManagement", moduleKey: "userManagement", roles: ["admin"], accessRoles: ["super_admin", "admin"] },
  "admin.settings": { enabled: true, featureKey: "settings", moduleKey: "settings", roles: ["admin"], accessRoles: ["super_admin"] },
  "employee.dashboard": { enabled: true, featureKey: "dashboard", roles: ["employee"], accessRoles: ["employee"] },
  "employee.profile": { enabled: true, featureKey: "profile", roles: ["employee"] },
  "employee.attendance": { enabled: true, featureKey: "attendance", roles: ["employee"] },
  "employee.leave": { enabled: true, featureKey: "leave", roles: ["employee"] },
  "employee.payroll": { enabled: true, featureKey: "payroll", roles: ["employee"] },
  "employee.letters": { enabled: true, featureKey: "letters", roles: ["employee"] },
  "hr.dashboard": { enabled: true, featureKey: "dashboard", moduleKey: "dashboard", roles: ["employee"], accessRoles: ["hr_manager"] },
  "recruiter.dashboard": { enabled: true, featureKey: "dashboard", moduleKey: "dashboard", roles: ["employee"], accessRoles: ["recruiter"] },
  "candidate.dashboard": { enabled: true, featureKey: "dashboard", roles: ["candidate"] },
  "candidate.profile": { enabled: true, featureKey: "profile", roles: ["candidate"] },
  "candidate.applications": { enabled: true, featureKey: "applications", roles: ["candidate"] },
  "candidate.status": { enabled: true, featureKey: "applications", roles: ["candidate"] },
  "candidate.documents": { enabled: true, featureKey: "documents", roles: ["candidate"] },
  "candidate.notifications": { enabled: true, featureKey: "notifications", roles: ["candidate"] },
  "candidate.stage2": { enabled: true, featureKey: "applications", roles: ["candidate"] },
  "candidate.joiningForm": { enabled: true, featureKey: "applications", roles: ["candidate"] },
  "joining.form": { enabled: true, featureKey: "joiningForms", roles: ["employee"] },
  apply: { enabled: true, featureKey: "applications", roles: ["candidate"] },
};
